language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

script:
  - npm test

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

addons:
  code_climate:
    repo_token: ba5df3970b5010419f55740dbf36de0cd02fe3e8cb52c30b1a017e0a3346f805
